name: nerfinvertor
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.0
  - pytorch=1.11.0=py3.8_cuda11.3_cudnn8.2.0_0
  - torchaudio=0.11.0=py38_cu113
  - torchvision=0.12.0=py38_cu113
  # - pytorch3d=0.7.2=py38_cu113_pyt1110
  - pip:
    - matplotlib==3.2.1
    - mrcfile==1.3.0
    - numpy==1.24.4
    - open3d==0.11.2
    - opencv-python==4.4.0.44
    - pandas==1.1.1
    - Pillow==6.0.0
    - plotly==4.9.0
    - python-dateutil==2.8.1
    - pytorch-fid==0.1.1
    - PyYAML==5.3.1
    - scikit-image==0.21.0
    - scikit-learn==1.3.0
    - scikit-video==1.1.11
    - scipy==1.10.1
    - tensorboard==1.15.0 #2.13.0
    - torch-fidelity==0.2.0
    - tensorboardX==2.2
    - sk-video==1.1.10
    - lpips==0.1.3
    - torch-ema
    - https://github.com/podgorskiy/dnnlib/releases/download/0.0.1/dnnlib-0.0.1-py3-none-any.whl
